version: '3.6'
services:
  app:
    image: ibrunotome/php:8.3.6-frankenphp
    command: php artisan octane:frankenphp --host=0.0.0.0 --port=8000 --max-requests=1
    ports:
      - '80:8000'
    volumes:
      - '.:/app'
      - './php.ini:/usr/local/etc/php/php.ini'
    networks:
      - local
    depends_on:
      - pgsql
      - redis
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  queue:
    image: ibrunotome/php:8.3.6-frankenphp
    command: php artisan horizon
    volumes:
      - '.:/var/www'
      - './php.ini:/usr/local/etc/php/php.ini'
    networks:
      - local
    depends_on:
      - pgsql
      - redis

  pgsql:
    image: postgres:16-alpine
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - 'localpgsql:/var/lib/postgresql/data'
    networks:
      - local
    healthcheck:
      test: [ 'CMD', 'pg_isready', '-q', '-d', '${DB_DATABASE}', '-U', '${DB_USERNAME}' ]

  redis:
    image: library/redis:7.2.3-alpine
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'localredis:/data'
    networks:
      - local
    healthcheck:
      test: [ 'CMD', 'redis-cli', 'ping' ]

networks:
  local:
    driver: bridge
volumes:
  localpgsql:
    driver: local
  localredis:
    driver: local
  localmeilisearch:
    driver: local
